# Generated by Django 5.2 on 2025-05-22 16:22

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Vendor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('phone_number', models.CharField(help_text='Include country code, e.g., +254712345678', max_length=15, validators=[django.core.validators.RegexValidator(message="Phone number must be in the format: '+254712345678'.", regex='^\\+?\\d{9,15}$')])),
                ('business_address', models.TextField(help_text='Enter full business address')),
            ],
        ),
        migrations.CreateModel(
            name='SellModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product', models.CharField(max_length=60)),
                ('unit', models.IntegerField()),
                ('description', models.TextField()),
                ('vendor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.vendor')),
            ],
        ),
    ]
